<?php
/**
 * Journal (blog) helpers — category filters and pagination.
 *
 * The static design filters the post grid in JavaScript, which can only ever
 * see the posts already on the page. That breaks as soon as the listing is
 * paginated, so the filters here are real links to category archives: filtering
 * happens in the query, and pagination then works inside the filtered set.
 * The markup and classes are unchanged, so the design is untouched.
 *
 * @package Aberdeen_Piano
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * The category currently being filtered on, if any.
 *
 * @return WP_Term|null
 */
function aberdeen_piano_current_category() {
	if ( ! is_category() ) {
		return null;
	}

	$term = get_queried_object();

	return ( $term instanceof WP_Term ) ? $term : null;
}

/**
 * Filter buttons: "All posts" followed by every category that has posts.
 *
 * @return array List of array( label, url, slug, active ).
 */
function aberdeen_piano_journal_filters() {
	$current = aberdeen_piano_current_category();

	$filters = array(
		array(
			'label'  => aberdeen_piano_journal_field( 'ap_journal_filters_all', 'journal.filters_all' ),
			'url'    => aberdeen_piano_journal_url(),
			'slug'   => 'all',
			'active' => null === $current,
		),
	);

	$categories = get_categories(
		array(
			'hide_empty' => true,
			'orderby'    => 'name',
			'order'      => 'ASC',
		)
	);

	foreach ( $categories as $category ) {
		$filters[] = array(
			'label'  => $category->name,
			'url'    => get_category_link( $category->term_id ),
			'slug'   => $category->slug,
			'active' => $current && $current->term_id === $category->term_id,
		);
	}

	/**
	 * Filter the Journal filter buttons.
	 *
	 * @param array $filters Filter definitions.
	 */
	return apply_filters( 'aberdeen_piano_journal_filters', $filters );
}

/**
 * The first category of a post, used for the card's chip and data-kind.
 *
 * @param int|WP_Post|null $post Optional post.
 * @return WP_Term|null
 */
function aberdeen_piano_post_category( $post = null ) {
	$categories = get_the_category( get_post_field( 'ID', $post ) );

	return $categories ? $categories[0] : null;
}

/**
 * Render the Journal pagination in the design's visual language.
 *
 * @param WP_Query|null $query Optional query; defaults to the main query.
 * @param string        $base  Optional listing URL. Required during an AJAX
 *                             request, where there is no current URL for
 *                             paginate_links() to build page links from.
 * @return void
 */
function aberdeen_piano_pagination( $query = null, $base = '' ) {
	global $wp_query;

	$query = $query instanceof WP_Query ? $query : $wp_query;

	if ( $query->max_num_pages < 2 ) {
		return;
	}

	$paged = max( 1, (int) get_query_var( 'paged' ) );

	$args = array(
		'total'     => $query->max_num_pages,
		'current'   => $paged,
		'mid_size'  => 1,
		'end_size'  => 1,
		'type'      => 'array',
		'prev_text' => '&#8592; ' . aberdeen_piano_journal_field( 'ap_journal_prev_label', 'journal.prev_label' ),
		'next_text' => aberdeen_piano_journal_field( 'ap_journal_next_label', 'journal.next_label' ) . ' &#8594;',
	);

	if ( ! $base ) {
		$base = aberdeen_piano_pagination_base();
	}

	if ( $base ) {
		$args['base']   = trailingslashit( $base ) . user_trailingslashit( 'page/%#%', 'paged' );
		$args['format'] = '';
	}

	$links = paginate_links( $args );

	if ( ! $links ) {
		return;
	}

	printf(
		'<nav class="journal-pagination reveal" aria-label="%s">',
		esc_attr__( 'Journal pages', 'aberdeen-piano' )
	);

	foreach ( $links as $link ) {
		// paginate_links() returns <a class="page-numbers"> / <span class="page-numbers current">.
		echo str_replace( 'page-numbers', 'page-numbers filter', $link ); // phpcs:ignore WordPress.Security.EscapingOutput.OutputNotEscaped -- generated by paginate_links().
	}

	echo '</nav>';

	printf(
		'<p class="pagination-summary">%s</p>',
		esc_html(
			sprintf(
				/* translators: 1: current page, 2: total pages. */
				__( 'Page %1$s of %2$s', 'aberdeen-piano' ),
				number_format_i18n( $paged ),
				number_format_i18n( $query->max_num_pages )
			)
		)
	);
}

/**
 * The document title for the Journal listing.
 *
 * The posts page's own title is what WordPress puts in <title>, and that is
 * still "Blog" on this install even though the slug, the menu item and every
 * heading now read Journal. Rather than depend on that one field being kept in
 * step, the listing is titled from the theme, defaulting to "Journal" — the
 * same word the navigation and the slug use. Change it in inc/defaults.php or
 * through the aberdeen_piano_journal_document_title filter below.
 *
 * Category, tag, author, date and search views are left to WordPress, which
 * already titles them from the term or query.
 *
 * @param array $parts Document title parts.
 * @return array
 */
function aberdeen_piano_journal_document_title( $parts ) {
	if ( ! is_home() || is_front_page() ) {
		return $parts;
	}

	$title = trim( wp_strip_all_tags( (string) aberdeen_piano_default( 'journal.document_title' ) ) );

	/**
	 * Filter the Journal listing's document title.
	 *
	 * @param string $title The title about to be used.
	 */
	$title = apply_filters( 'aberdeen_piano_journal_document_title', $title );

	if ( '' !== $title ) {
		$parts['title'] = $title;
	}

	return $parts;
}
add_filter( 'document_title_parts', 'aberdeen_piano_journal_document_title' );

/**
 * The heading shown on the Journal hero for the current view.
 *
 * @return string HTML, already escaped.
 */
function aberdeen_piano_journal_title() {
	if ( is_search() ) {
		return sprintf(
			/* translators: %s: search query. */
			esc_html__( 'Results for %s', 'aberdeen-piano' ),
			'<em>' . esc_html( get_search_query() ) . '</em>'
		);
	}

	if ( is_category() || is_tag() || is_tax() ) {
		return '<em>' . esc_html( single_term_title( '', false ) ) . '</em>';
	}

	if ( is_author() ) {
		return '<em>' . esc_html( get_the_author() ) . '</em>';
	}

	if ( is_year() || is_month() || is_day() ) {
		return '<em>' . esc_html( get_the_archive_title() ) . '</em>';
	}

	$white = esc_html( aberdeen_piano_journal_field( 'ap_journal_title_white', 'journal.title_white' ) );
	$black = esc_html( aberdeen_piano_journal_field( 'ap_journal_title_black', 'journal.title_black' ) );
	$em    = esc_html( aberdeen_piano_journal_field( 'ap_journal_title_em', 'journal.title_em' ) );

	return '<span class="piano-line"><span class="white-key">' . $white . '</span> <span class="black-key">' . $black . '</span></span><br><em>' . $em . '</em>';
}

/**
 * Listing URL that pagination links should be built from.
 *
 * During a normal request paginate_links() infers this from the current URL.
 * In an AJAX request there is no such URL, so the endpoint sets it here before
 * rendering the shared posts template part.
 *
 * @param string|null $base Pass a URL to set it; omit to read it.
 * @return string
 */
function aberdeen_piano_pagination_base( $base = null ) {
	static $stored = '';

	if ( null !== $base ) {
		$stored = $base;
	}

	return $stored;
}
